### ISSUE TITLE
Flatpak Sigil - Plugins cannot open java 

### ISSUE THREAD

**Issue by pj7** [flathub/com.sigil_ebook.Sigil#15]
Using flatpak Sigil 1.9.20 - it is impossible to use the most common plugin for checking the epub file, EpubCheck. When trying to run EpubCheck, it cannot locate Java which is however correctly installed in /usr/bin/java.

The same is true for the import plugin, ODTImport, which is used to create an epub file from a LibreOffice odt file input.

It would seem likely that the  SDK Extension for OpenJDK 17 should be incorporated in the Flatpak manifest. 

Would this be possible?

**Comment by catsout** [comment]
Added.  
Please follow the readme.

**Comment by catsout** [comment]
The new version will be pushed after about 4 hours.
