### ISSUE TITLE
Wayland Issue Trying to Open File Picker

### ISSUE THREAD

**Issue by pjkaufman** [flathub/com.sigil_ebook.Sigil#27]
Hey, I am running Wayland on Pop Os! 22.04 in Sway 1.7 with Sigil version 2.0.1.

I am running it via the flatpak and I get an error when I try to open the file picker: `Warning: Wayland does not support QWindow::requestActivate()`. I have seen a couple of threads out there implying this may be an issue with the QT version, but I am not sure if that is actually the case.

Is there a recommended way to get around this issue?
So far I can get around this by passing in the file to open as the first param to the flatpak run command for Sigil, but it would be best if I could use the file picker as needed. I do have xwalyand installed, but that does not seem to change anything around this error.

Please let me know if I can help out in any way! Thanks!

**Comment by lidgnulinux** [comment]
Do you have xdg-desktop-portal-gtk installed ?

**Comment by pjkaufman** [comment]
I don't recall if I did at the time. But I do now. I can double check if that was the issue and then let you know if this can be closed as operator error/environment configuration error.

**Comment by pjkaufman** [comment]
This is an issue that was likely caused by not having `xdg-desktop-portal-gtk` installed. So I am going to close this. Thank you for your time and making this app available as a Flatpak!
